package com.taskapp.taskapp.controllers;

import java.util.List;

import com.taskapp.taskapp.entities.User;
import com.taskapp.taskapp.repositories.UserRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloWorldController {
  // Autowired is magic annotation wherein spring takes care of getting an instantiated obj that will implement whatever interface is
  // listed and then assign it to the variable
  @Autowired
  private UserRepository userRepository;

  @GetMapping("/users")
  public @ResponseBody Iterable<User> getUsers() {
    return userRepository.findAll();  }
}

// @Controller // This means that this class is a Controller
// @RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
// public class MainController {
//   @Autowired // This means to get the bean called userRepository
//          // Which is auto-generated by Spring, we will use it to handle the data
//   private UserRepository userRepository;

//   @PostMapping(path="/add") // Map ONLY POST Requests
//   public @ResponseBody String addNewUser (@RequestParam String name
//       , @RequestParam String email) {
//     // @ResponseBody means the returned String is the response, not a view name
//     // @RequestParam means it is a parameter from the GET or POST request

//     User n = new User();
//     n.setName(name);
//     n.setEmail(email);
//     userRepository.save(n);
//     return "Saved";
//   }

//   @GetMapping(path="/all")
//   public @ResponseBody Iterable<User> getAllUsers() {
//     // This returns a JSON or XML with the users
//     return userRepository.findAll();
//   }
// }